### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bswck** [bswck/mempip#1]
# Roadmap

## Python API
- [ ] `mempip.install()` → Install packages with all its dependencies.
- [ ] `mempip.download()` → Download packages. Return a tree of the downloaded packages.
- [ ] `mempip.uninstall()` → Uninstall packages.
- [ ] `mempip.freeze()` → Output installed packages in requirements format.
- [ ] `mempip.inspect()` → Inspect the Python environment.
- [ ] `mempip.list()` → List installed packages.
- [ ] `mempip.show()` → Show information about installed packages.
- [ ] `mempip.check()` → Verify installed packages have compatible dependencies.
- [ ] `mempip.config()` → Manage local and global configuration.
- [ ] `mempip.cache()` → Inspect and manage pip's wheel cache.
- [ ] `mempip.index()` → Inspect information available from package indexes.
- [ ] `mempip.hash()` → Compute hashes of package archives.
- [ ] `mempip.completion()` → A helper command used for command completion.
- [ ] `mempip.debug()` → Show information useful for debugging.
- [ ] `mempip.help()` → Show help for commands.

**Comment by bswck** [comment]
Thanks @kurtmckee for creating sqliteimport, which might be useful in designing in-memory modules.

**Comment by kurtmckee** [comment]
You're welcome! It's currently at the proof-of-concept stage and doesn't yet work beyond the simple demo at the root of the repo (for example, `import package.subpackage` doesn't work), but it's letting me explore a part of Python that I've never dug into before, and I'm excited to continue exploring!

**Comment by bswck** [comment]
> You're welcome! It's currently at the proof-of-concept stage and doesn't yet work beyond the simple demo at the root of the repo (for example, `import package.subpackage` doesn't work), but it's letting me explore a part of Python that I've never dug into before, and I'm excited to continue exploring!

@kurtmckee Cool. I'd be interested in developing a collection of backends (including SQLite, Redis) for partitioning dependencies by tags/dates for the ease of rolling back, and loading modules from these. Let me know if you're interested.

[I'm a bit experienced with the import system](https://github.com/bswck/slothy). Please send me an invite on Discord if you're interested in collaboration: bswck.
