### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bswck** [bswck/mempip#1]
# Roadmap

## Python API
- [ ] `mempip.install()` → Install a packages with all its dependencies.
- [ ] `mempip.download()` → Download a single package. Return a `DownloadedPackage()` object with package metadata, dependencies etc.
- [ ] `mempip.uninstall()` → Uninstall packages.
- [ ] `mempip.freeze()` → Output installed packages in requirements format.
- [ ] `mempip.inspect()` → Inspect the Python environment.
- [ ] `mempip.list()` → List installed packages.
- [ ] `mempip.show()` → Show information about installed packages.
- [ ] `mempip.check()` → Verify installed packages have compatible dependencies.
- [ ] `mempip.config()` → Manage local and global configuration.
- [ ] `mempip.search()` → Search PyPI for packages.
- [ ] `mempip.cache()` → Inspect and manage pip's wheel cache.
- [ ] `mempip.index()` → Inspect information available from package indexes.
- [ ] `mempip.hash()` → Compute hashes of package archives.
- [ ] `mempip.completion()` → A helper command used for command completion.
- [ ] `mempip.debug()` → Show information useful for debugging.
- [ ] `mempip.help()` → Show help for commands.
